site_name: Himon
site_url: https://himon.readthedocs.io/en/latest/
site_description: A Python wrapper for League of Comic Geeks.
site_author: Jonah Jackson

copyright: MIT

repo_url: https://github.com/Buried-In-Code/Himon
repo_name: Buried-In-Code/Himon

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
  icon:
    repo: material/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: material/github
      link: https://github.com/Buried-In-Code
    - icon: material/language-python
      link: https://pypi.org/project/himon/
    - icon: material/mastodon
      link: https://fosstodon.org/@BuriedInCode
    - icon: simple/matrix
      link: https://matrix.to/#/#The-Dev-Environment:matrix.org

markdown_extensions:
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  - himon:
      - Package: himon/__init__.md
      - exceptions: himon/exceptions.md
      - league_of_comic_geeks: himon/league_of_comic_geeks.md
      - sqlite_cache: himon/sqlite_cache.md
  - himon.schemas:
      - Package: himon/schemas/__init__.md
      - comic: himon/schemas/comic.md
      - generic: himon/schemas/generic.md
      - series: himon/schemas/series.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: True
            show_root_full_path: False
            show_category_heading: True
            # Docstrings
            docstring_style: google
            docstring_section_style: spacy
            line_length: 100
            merge_init_into_class: True
            show_signature_annotations: True
            # Additional
            show_source: False
  - include-markdown
