[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python",
  "Topic :: Internet",
  "Typing :: Typed"
]
dependencies = [
  "pydantic >= 2.4.2",
  "ratelimit >= 2.2.1",
  "requests >= 2.31.0"
]
description = "A Python wrapper for League of Comic Geeks."
dynamic = ["version"]
keywords = ["comic", "comics", "metadata"]
license = "GPL-3.0-or-later"
maintainers = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
name = "Himon"
readme = "README.md"
requires-python = ">= 3.8"

[project.optional-dependencies]
dev = [
  "pre-commit >= 3.4.0"
]
docs = [
  "mkdocs >= 1.5.3",
  "mkdocs-include-markdown-plugin >= 6.0.1",
  "mkdocs-material >= 9.4.4",
  "mkdocstrings[python] >= 0.23.0"
]
test = [
  "pytest >= 7.4.2",
  "pytest-cov >= 4.1.0",
  "pytest-pretty >= 1.2.0"
]

[project.urls]
Documentation = "https://himon.readthedocs.io/en/latest/"
Homepage = "https://pypi.org/project/Himon"
Issues = "https://github.com/Buried-In-Code/Himon/issues"
Source = "https://github.com/Buried-In-Code/Himon"

[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312", "py38", "py39"]

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["himon"]

[tool.hatch.version]
path = "himon/__init__.py"

[tool.pytest.ini_options]
addopts = ["--cov"]

[tool.ruff]
fix = true
ignore = [
  "D107",
  "EXE",
  "FBT",
  "PLR2004",
  "TCH"
]
line-length = 100
output-format = "grouped"
select = ["ALL"]
show-fixes = true
target-version = "py38"

[tool.ruff.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.isort]
combine-as-imports = true

[tool.ruff.mccabe]
max-complexity = 18

[tool.ruff.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.field_validator"]

[tool.ruff.per-file-ignores]
"himon/schemas/*.py" = ["FA100"]
"tests/test_*.py" = ["S101"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.pylint]
max-args = 7
