[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { name = "BuriedInCode", email = "BuriedInCode@tuta.io" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Internet",
  "Typing :: Typed"
]
dependencies = [
  "pydantic >= 1.10.2",
  "requests >= 2.28.1",
  "ratelimit >= 2.2.1"
]
description = "A Python wrapper for League of Comic Geeks."
dynamic = ["version"]
keywords = ["comics", "comic", "metadata"]
license = "GPL-3.0-or-later"
name = "Himon"
readme = "README.md"
requires-python = ">= 3.7"

[project.optional-dependencies]
dev = [
  "pre-commit >= 2.20.0",
]
docs = [
  "mkdocs >= 1.4.1",
  "mkdocstrings[python] >= 0.19.0",
  "mkdocs-include-markdown-plugin >= 3.9.1"
]
test = [
  "pytest >= 7.2.0",
  "pytest-cov >= 4.0.0",
  "tox >= 3.27.0",
  "tox-pyenv >= 1.1.0"
]

[project.urls]
Documentation = "https://himon.readthedocs.io/en/latest/"
Homepage = "https://pypi.org/project/Himon"
Issues = "https://github.com/Buried-In-Code/Himon/issues"
Source = "https://github.com/Buried-In-Code/Himon"

[tool.bandit]
recursive = true
skips = ["B101"]

[tool.black]
line-length = 100
target-version = ["py37", "py38", "py39", "py310", "py311"]

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["himon"]

[tool.hatch.version]
path = "himon/__init__.py"

[tool.isort]
default_section = "THIRDPARTY"
line_length = 100
profile = "black"

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]
