[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Natural Language :: English",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python",
  "Topic :: Internet",
  "Typing :: Typed"
]
dependencies = [
  "eval-type-backport >= 0.1.3; python_version < \"3.10\"",
  "pydantic >= 2.6.4",
  "ratelimit >= 2.2.1",
  "requests >= 2.31.0"
]
description = "A Python wrapper for League of Comic Geeks."
dynamic = ["version"]
keywords = ["comic", "comics", "metadata"]
license = "GPL-3.0-or-later"
maintainers = [
  {email = "BuriedInCode@tuta.io", name = "BuriedInCode"}
]
name = "Himon"
readme = "README.md"
requires-python = ">= 3.8"

[project.optional-dependencies]
dev = [
  "pre-commit >= 3.5.0"
]
docs = [
  "mkdocs >= 1.5.3",
  "mkdocs-include-markdown-plugin >= 6.0.4",
  "mkdocs-material >= 9.5.13",
  "mkdocstrings[python] >= 0.24.1"
]
test = [
  "pytest >= 8.1.1",
  "pytest-cov >= 4.1.0",
  "tox >= 4.14.1"
]

[project.urls]
Documentation = "https://himon.readthedocs.io/en/latest/"
Homepage = "https://pypi.org/project/Himon"
Issues = "https://github.com/Buried-In-Code/Himon/issues"
Source = "https://github.com/Buried-In-Code/Himon"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
source = ["himon"]

[tool.hatch.version]
path = "himon/__init__.py"

[tool.pytest.ini_options]
addopts = ["--cov"]

[tool.ruff]
fix = true
line-length = 100
output-format = "grouped"
show-fixes = true
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "native"
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
  "COM812",
  "D107",
  "EXE",
  "FBT",
  "PLR2004",
  "TCH"
]
ignore-init-module-imports = true
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.field_validator"]

[tool.ruff.lint.per-file-ignores]
"tests/test_*.py" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 7
