name: Publishing

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi:
    name: Publish to PyPI
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3
      #----------------------------------------------
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup PDM
        run: pip install pdm
      #----------------------------------------------
      - name: Publish project
        run: pdm publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
