name: Publishing

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi:
    name: Publish to PyPI
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.11'
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup environment
        run: pip install twine build packaging
      - name: Build project
        run: python -m build
      - name: Check dist
        run: twine check dist/*
      - name: Publish project
        run: twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
